services:
    webserver:
        build: .
        restart: always
        volumes:
            - ./www:/var/www/html
        ports:
            - "8081:80"
        
        
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql


    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "8082:80" 

    # apache:
    #     image: httpd:2.4
    #     ports:
    #         - "8080:80"
